using System;

namespace BnPBaseFramework.Reporting.Reports
{
    public class TemplatesForHtmlReport
    {      
        public static String GetScreenShotsTemplate()
        {
            return "<div class=\"panel panel-default\">\n"
            + "    <div class=\"panel-heading\">\n"
            + "        <h4 class=\"panel-title\">\n"
            + "            <a data-toggle=\"collapse\" href=\"#collapseScenario0_<%=ScreenShotNumber%>\">\n"
            + "                <i class=\"glyphicon glyphicon-chevron-right\"></i>\n"
            + "                <i class=\"glyphicon glyphicon-chevron-down\"></i>\n"
            + "                <b>ScreenShots - Test Case Flow</b>\n"
            + "            </a>\n"
            + "        </h4>\n"
            + "    </div>\n"
            + "    <div id=\"collapseScenario0_<%=ScreenShotNumber%>\" class=\"panel-collapse collapse\">\n"
            + "        <div class=\"panel-body\">\n"
            + "            <div class=\"description\">\n";
        }

        public static String GetTestCaseEndTemplate()
        {
            return "            </div>\n" + "        </div>\n" + "    </div>\n" + "</div>";
        }

        public static String GetTestCaseStartTemplate()
        {
            return "<div class=\"col-lg-6 col-md-6\">\n"
            + "    <div class=\"panel panel-default\">\n"
            + "        <div class=\"panel-heading\">\n"
            + "            <h4 class=\"panel-title\">\n"
            + "                <a data-toggle=\"collapse\" href=\"#collapseFeature_<%=Test_Case_Number%>\">\n"
            + "                    <i class=\"glyphicon glyphicon-chevron-right\"></i>\n"
            + "                    <i class=\"glyphicon glyphicon-chevron-down\"></i>\n"
            + "                    <b>Test Case :</b><%=Test_Case_Name%>\n"
            + "                    <span class=\"label-container\">\n"
            + "                      <span class=\"label label-success\" title=\"Passed\">Passed</span>\n"
            + "                       <span class=\"label label-danger\" title=\"Failed\">Failed</span>\n"
            + "                    </span>\n"
            + "                </a>\n"
            + "            </h4>\n"
            + "        </div>\n"
            + "        <div id=\"collapseFeature_<%=Test_Case_Number%>\" class=\"panel-collapse collapse\">\n"
            + "            <div class=\"panel-body\">\n"
            + "                <div class=\"description\">\n"
            + "                    <b>Test Case : </b> <%=Test_Case_Name_Afer_Expansion%><br />\n"
            + "                    <b>Start Time: </b> <%=Test_Case_Start%><br />\n"
            + "                    <b>End Time  : </b> <%=Test_Case_End%><br />\n"
            + "                    <b>Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: </b> <%=Test_Case_Status%></br>\n"
            + "                    <%=ErrorMessage%>\n"
            + "                    <%=ScreenShot%>\n"
            + "                </div>\n"
            + "\n"
            + "\n";
        }

        


    public static String GetTestStepTemplate()
        {
            return "<div class=\"panel panel-default\">\n"
            + "    <div class=\"panel-heading\">\n"
            + "        <h4 class=\"panel-title\">\n"
            + "            <a data-toggle=\"collapse\" href=\"#collapseScenario0_<%=StepNumber%>\">\n"
            + "                <i class=\"glyphicon glyphicon-chevron-right\"></i>\n"
            + "                <i class=\"glyphicon glyphicon-chevron-down\"></i>\n"
            + "                <b>Test Step:</b><%=Test_Step_Name%>\n"
            + "                <span class=\"label-container\">\n"
            + "                      <span class=\"label label-success\" title=\"Passed\">Passed</span>\n"
            + "                       <span class=\"label label-danger\" title=\"Failed\">Failed</span>\n"
            + "                    </span>\n"
            + "            </a>\n"
            + "        </h4>\n"
            + "    </div>\n"
            + "    <div id=\"collapseScenario0_<%=StepNumber%>\" class=\"panel-collapse collapse\">\n"
            + "        <div class=\"panel-body\">\n"
            + "            <div class=\"description\">\n"
            + "                <b>Test Step: </b><%=Test_Step_Name_If_Wrapped%><br />\n"
            + "                <b>Start Time: </b><%=Step_Start_Time%><br />\n"
            + "                <b>End Time  : </b><%=Step_End_Time%><br />\n"            
            + "                <b>Status : </b><%=Step_Status%><br />\n"
            + "                <%=Output_Status%><br />\n"
            + "                <b>ScreenShot : </b>\n"
            + "                <%=ScreenShot%>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "    </div>\n"
            + "</div>";
        }

        public static String GetTestSuiteEndTemplate()
        {
            return   "<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\n"
        + "<script src=\"https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js\"></script>\n"
        + "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js\"></script>\n"
        + "<script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\n"
        + "<script type=\"text/javascript\">\n"
        + "        google.load(\"visualization\", \"1\", {packages: [\"corechart\"]});\n"
        + "        google.setOnLoadCallback(function() {drawChart({\n"
        + "                                                            \"title\" : \"Test_Cases\",\n"
        + "                                                            \"failed\" : <%=FailedTestCases%>,\n"
        + "                                                            \"passed\" : <%=PassedTestCases%>\n"
        + "                                                        })\n"
        + "                                            });\n"
        + "    </script>\n"
        + "<script>\n"
        + "      $(document).ready(function() {\n"
        + "    $('.collapse').on('hide.bs.collapse', function(e) {\n"
        + "        e.stopPropagation();\n"
        + "        $(this).prev().removeClass('open');\n"
        + "    }).on('show.bs.collapse', function(e) {\n"
        + "        e.stopPropagation();\n"
        + "        $(this).prev().addClass('open');\n"
        + "    });\n"
        + "\n"
        + "    $('a.toggle').on('click', function() {\n"
        + "        if ($(this).text() === 'Screenshot -') {\n"
        + "            $(this).text('Screenshot +');\n"
        + "            $(this).siblings('a.screenshot').find('img').hide();\n"
        + "        } else {\n"
        + "            $(this).text('Screenshot -');\n"
        + "            $(this).siblings('a.screenshot').find('img').show();\n"
        + "        }\n"
        + "    });\n"
        + "    var $generated = $('.generated-on');\n"
        + "\n"
        + "    $generated.text('Generated ' + moment($generated.text()).fromNow());\n"
        + "\n"
        + "\n"
        + "});\n"
        + "\n"
        + "      function drawChart(chartData) {\n"
        + "    var data = google.visualization.arrayToDataTable([\n"
        + "        ['Task', 'Cucumber Results'],\n"
        + "        ['Passed', chartData.passed],\n"
        + "        ['Failed', chartData.failed],\n"
        + "        ['Pending', chartData.notdefined],\n"
        + "        ['Skipped', chartData.skipped]\n"
        + "    ]);\n"
        + "\n"
        + "    var total = chartData.passed + chartData.failed + (chartData.notdefined || 0) + (chartData.skipped || 0);\n"
        + "    var title;\n"
        + "\n"
        + "    if (total === 1) {\n"
        + "        title = total + ' ' + chartData.title.slice(0, -1)\n"
        + "    } else {\n"
        + "        title = total + ' ' + chartData.title;\n"
        + "    }\n"
        + "\n"
        + "    var options = {\n"
        + "        width: '100%',\n"
        + "        height: 240,\n"
        + "        title: title,\n"
        + "        is3D: true,\n"
        + "        colors: ['#5cb85c', '#d9534f', '#5bc0de', '#f0ad4e'],\n"
        + "        fontSize: '13',\n"
        + "        fontName: '\"Helvetica Neue\", \"Helvetica\", Helvetica, Arial, sans-serif',\n"
        + "        slices: {\n"
        + "            1: {offset: 0.4},\n"
        + "            2: {offset: 0.4},\n"
        + "            3: {offset: 0.4}\n"
        + "        },\n"
        + "        titleTextStyle: {\n"
        + "            fontSize: '13',\n"
        + "            color: '#5e5e5e'\n"
        + "        }\n"
        + "    };\n"
        + "\n"
        + "    var chart = new google.visualization.PieChart(document.getElementById('piechart_' + chartData.title.toLowerCase()));\n"
        + "    chart.draw(data, options);\n"
        + "}\n"
        + "    </script>\n"
        + "</body>\n"
        + "</html>";
        }

        public static String GetTestSuiteStartTemplate()
        {
            return "<!DOCTYPE html>\n"
        + "<html>\n"
        + "<head>\n"
        + "    <title>BnP Test Automation Results</title>\n"
        + "    <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">\n"
        + "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n"
        + "    <style type=\"text/css\">\n"
        + "      .panel-heading {\n"
        + "    padding: 0;\n"
        + "}\n"
        + "\n"
        + "@media (min-width: 768px) {\n"
        + "    .pull-right-lg {\n"
        + "        float: left;\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "@media (min-width: 992px) and (max-width: 1199px) {\n"
        + "    .pull-right-lg {\n"
        + "        float: right;\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "@media (min-width: 768px) and (max-width: 991px) {\n"
        + "    .pull-right-lg {\n"
        + "        float: right;\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "@media (min-width: 1200px) {\n"
        + "    .pull-right-lg {\n"
        + "        float: right;\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + ".left {\n"
        + "    float: left;\n"
        + "}\n"
        + "\n"
        + ".metadata {\n"
        + "    overflow: auto;\n"
        + "    letter-spacing: 0.2px;\n"
        + "    border-color: white;\n"
        + "    line-height: 1.6;\n"
        + "    color: #4d4d4d;\n"
        + "    font-family: \"Helvetica Neue\", \"Helvetica\", Helvetica, Arial, sans-serif;\n"
        + "    font-size: 13px;\n"
        + "    padding-bottom:3px;\n"
        + "}\n"
        + "\n"
        + ".panel-heading a {\n"
        + "    padding: 10px 15px;\n"
        + "    display: block;\n"
        + "    position: relative;\n"
        + "    text-decoration: none;\n"
        + "}\n"
        + "\n"
        + ".panel-heading i.glyphicon-chevron-down {\n"
        + "    display: none;\n"
        + "}\n"
        + "\n"
        + ".panel-heading i.glyphicon-chevron-right {\n"
        + "    display: inline-block;\n"
        + "}\n"
        + "\n"
        + ".panel-heading.open i.glyphicon-chevron-down {\n"
        + "    display: inline-block;\n"
        + "}\n"
        + "\n"
        + ".panel-heading.open i.glyphicon-chevron-right {\n"
        + "    display: none;\n"
        + "}\n"
        + "\n"
        + ".generated-on {\n"
        + "    text-align: right;\n"
        + "    padding-bottom: 10px;\n"
        + "}\n"
        + "\n"
        + ".panel-title b {\n"
        + "    padding-right: 10px;\n"
        + "}\n"
        + "\n"
        + ".panel-heading .label-container {\n"
        + "    position: absolute;\n"
        + "    top: 8px;\n"
        + "    right: 8px;\n"
        + "}\n"
        + "\n"
        + ".panel-heading .label-container label {\n"
        + "    margin-left: 5px;\n"
        + "    padding: 5px;\n"
        + "}\n"
        + "\n"
        + ".navbar .label-container {\n"
        + "    position: absolute;\n"
        + "    right: 10px;\n"
        + "    top: 14px;\n"
        + "}\n"
        + "\n"
        + ".navbar {\n"
        + "    margin-bottom: 10px;\n"
        + "}\n"
        + "\n"
        + ".navbar .label {\n"
        + "    font-size: 20px;\n"
        + "}\n"
        + "\n"
        + ".navbar .project-name {\n"
        + "    position: absolute;\n"
        + "    top: 10px;\n"
        + "    left: 50%;\n"
        + "    margin-left: -100px;\n"
        + "    text-align: center;\n"
        + "    font-size: 20px;\n"
        + "    font-weight: bold;\n"
        + "}\n"
        + "\n"
        + ".tags {\n"
        + "    margin-left: 18px;\n"
        + "    margin-right: 20px;\n"
        + "    padding-top: 5px;\n"
        + "    margin-bottom: -4px;\n"
        + "}\n"
        + "\n"
        + ".tag {\n"
        + "    font-size: 13px;\n"
        + "    color: #696969;\n"
        + "    letter-spacing: 0.3px;\n"
        + "    font-weight: bold;\n"
        + "    font-family: \"Helvetica Neue\", \"Helvetica\", Helvetica, Arial, sans-serif;\n"
        + "}\n"
        + "\n"
        + ".chart {\n"
        + "    padding-bottom: 15px;\n"
        + "}\n"
        + "\n"
        + "div.chart div div svg rect {\n"
        + "    fill: #f5f5f5;\n"
        + "}\n"
        + "\n"
        + "table.arguments {\n"
        + "    margin-left: 30px;\n"
        + "}\n"
        + "\n"
        + ".screenshot {\n"
        + "    padding: 2% 0 2% 0;\n"
        + "}\n"
        + "\n"
        + ".scenarioTitle {\n"
        + "    width: 80%\n"
        + "}\n"
        + "\n"
        + ".description {\n"
        + "    background-color: white;\n"
        + "    border-color: white;\n"
        + "    line-height: 1.6;\n"
        + "    color: #6f6f6f;\n"
        + "    font-weight: 400;\n"
        + "    font-family: \"Helvetica Neue\", \"Helvetica\", Helvetica, Arial, sans-serif;\n"
        + "    font-size: 14px;\n"
        + "    padding:  0.1em 0.5em 1.2em 1.5em\n"
        + "}\n"
        + "\n"
        + "#scenario-description {\n"
        + "    padding-bottom:  1em;\n"
        + "    padding-left: 0.2em;\n"
        + "}\n"
        + "\n"
        + ".scrollBar {\n"
        + "    overflow-x: scroll;\n"
        + "}\n"
        + "\n"
        + "table {\n"
        + "    border-collapse: collapse;\n"
        + "}\n"
        + "\n"
        + "table, th, td {\n"
        + "    border: 1px solid black;\n"
        + "}\n"
        + "\n"
        + "th, td {\n"
        + "    text-align: left;\n"
        + "    padding: 8px;\n"
        + "}\n"
        + "\n"
        + "th {\n"
        + "    background-color: #f5f5f5;\n"
        + "    color: black;\n"
        + "}\n"
        + "\n"
        + ".info {\n"
        + "    background-color: #fbfbfb;\n"
        + "}\n"
        + "\n"
        + ".step-duration {\n"
        + "    float: right;\n"
        + "}\n"
        + "\n"
        + ".footer-div {\n"
        + "    text-align: right;\n"
        + "    vertical-align: middle;\n"
        + "    height:3.5%;\n"
        + "    width:100%;\n"
        + "}\n"
        + "\n"
        + ".footer-container {\n"
        + "    margin-right: 10px;\n"
        + "    margin-top: 5px;\n"
        + "    width:18%;\n"
        + "    z-index: 10;\n"
        + "    position: absolute;\n"
        + "    right: 0;\n"
        + "    bottom: 10px;\n"
        + "    text-align: center;\n"
        + "    background-color: transparent;\n"
        + "}\n"
        + "\n"
        + ".footer-link {\n"
        + "    font-size: 13px;\n"
        + "    float: right;\n"
        + "}\n"
        + "\n"
        + ".footer-link:hover {\n"
        + "    color: darkgray;\n"
        + "}\n"
        + "\n"
        + "    </style>\n"
        + "    <meta charset=\"UTF-8\">\n"
        + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        + "</head>\n"
        + "<body>\n"
        + "<ul class=\"nav nav-pills\" display:\"none;\">\n"
       // + "    <li class=\"active\"><a data-toggle=\"pill\" href=\"#results\">Build Result</a></li>\n"
        + "</ul>\n"
        + "<div class=\"tab-content\">\n"
        + "<div id=\"results\" class=\"tab-pane fade in active\">\n"
        + "<div class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\n"
        + "    <div class=\"container\">\n"
        + "        <div class=\"navbar-header\">\n"
        + "            <a class=\"navbar-brand\"></a>\n"
        + "            <div class=\"project-name visible-md visible-lg\">Execution Results</div>\n"
        + "            <div class=\"label-container\">\n"
        + "                <span class=\"label label-success\" title=scenarios>Passed: <%=PassedTestCases%></span>\n"
        + "                <span class=\"label label-danger\" title=scenarios>Failed: <%=FailedTestCases%></span>\n"
        + "            </div>\n"
        + "        </div>\n"
        + "    </div>\n"
        + "</div>\n"
        + "\n"
        + "<div class=\"container\">\n"
        + "\n"
        + "    <div class=\"row\">\n"
        + "        <div class=\"chart col-lg-6 col-md-6\" id=\"piechart_test_cases\"></div>\n"
        + "        <div id=\"logOutput\" class=\"\" style=\"width:100%;heigh:100%\">\n"
        + "            <div class=\"panel-body\">\n"
        + "                <div class=\"row\">\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong>Suite Name :</strong><%=Suite_Name%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong> Suite Start Time : </strong><%=Suite_StartTime%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong> Suite End Time :</strong><%=Suite_EndTime%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong> Application Under Test :</strong><%=Application_UnderTest%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong> Environment :</strong><%=Env_Name%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong> Build Number :</strong><%=Build_Number%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                    <div class=\"clearfix metadata col-xs-12 col-sm-6 col-md-6 col-lg-6\">\n"
        + "                        <div class=left>\n"
        + "                            <strong> Browser Name :</strong><%=Browser_Name%>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "\n"
        + "                </div>\n"
        + "            </div>\n"
        + "        </div>\n"
        + "\n"
        + "    </div>\n"
        + "\n"
        + "\n"
        + "    <div class=\"row\">\n";
        }
    }

}
